### ISSUE TITLE
游客点击‘立即购买’按钮，右上角‘立即登录’提示多余

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#110]
- [前置条件] 
游客进入万人车汇首页

- [操作步骤] 
点击商品上面‘立即购买’按钮

- [预期结果]
系统提示‘需要先登录’并跳转到手机验证码登录页面，右上角的‘立即登录’提示为多余

**Comment by shindouhiro** [comment]
已经去除，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
