### ISSUE TITLE
游客点击‘添加购物车’图标，右上角‘立即登录’提示信息多余

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#111]
- [前置条件] 
游客进入万人车汇首页
- [操作步骤] 
点击商品上面‘添加购物车’图标
- [预期结果] 
系统提示‘需要先登录’并跳转到手机验证码登录页面，提示信息‘立即登录’多余
![bug](https://user-images.githubusercontent.com/40376906/42364420-afdcc61e-812d-11e8-80dd-29f3874e80ec.png)

**Comment by shindouhiro** [comment]
已经去除提示，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
