### ISSUE TITLE
新建联系方式页面当电话号码为空时，无‘此处为必填项’提示，且姓名已填写的情况下有提示

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#113]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’
2.点击‘请填写您的联系方式’
3.点击‘新建’按钮
4.输入正确姓名
5.电话号码不输入
6.输入正确收货地址
7.输入正确车牌号码
8.点击‘保存’按钮
- [预期结果] 
电话号码输入框下方提示‘此处为必填项’
- [实际结果] 
1.电话号码输入框下方无提示‘此处为必填项’
2.您的姓名输入框下方提示‘此处为必填项’
![bug-](https://user-images.githubusercontent.com/40376906/42367489-fe17fcd2-8136-11e8-9651-1337be5f1c66.png)

**Comment by shindouhiro** [comment]
已经修改，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
