### ISSUE TITLE
新建联系方式页面当您的姓名和收货地址为空提示‘此处为必填项’后，已输入姓名和收货地址时，提示信息依然存在

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#114]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’
2.点击‘请填写您的联系方式’
3.点击‘新建’按钮
4.不输入姓名
5.输入正确电话号码
6.不输入电话号码
7.输入正确车牌号码
8.点击‘保存’按钮
9.再输入正确姓名
10.再输入收货地址
- [预期结果] 
1.当为空的时候输入框下方提示‘此处为必填项’
2.当再次填写姓名和收货地址后，提示信息应不再显示
- [实际结果] 
已填写姓名和收货地址后，提示信息依然存在
![bug-](https://user-images.githubusercontent.com/40376906/42368216-08f4974e-8139-11e8-9999-a7adfb537cac.png)

**Comment by shindouhiro** [comment]
功能修复，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
