### ISSUE TITLE
新建联系方式页面‘收获地址‘的’获‘字为错别字

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#115]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’
2.点击‘请填写您的联系方式’
3.点击‘新建’按钮
- [预期结果] 
进入新建联系方式页面，’收获地址‘正确应为’收货地址‘
- [实际结果] 
’收获地址‘

**Comment by shindouhiro** [comment]
已经修改，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
