### ISSUE TITLE
验证普通用户在推荐购买黑卡窗口点击‘立即购买’按钮时系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#16]
- [预置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的店铺’ 
2.点击‘新加商品’ 
3.点击‘立即购买’
- [预期结果] 
1.显示下拉列表‘新加商品’和‘正在出售商品’两个选项
2.弹出‘推荐购买黑卡窗口’
3.跳转到万人车汇黑卡产品介绍页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
