### ISSUE TITLE
我的银行卡页面解除银行卡绑定功能不能实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#163]
- [前置条件] 
1.用户已登录，进入个人中心页面
2.用户已绑定银行卡
- [操作步骤] 
1.点击‘我的银行卡’，进入的我的银行卡页面
2.页面显示用户绑定的银行卡
3.点击银行卡右下角‘解除绑定’按钮
- [预期结果]
 应弹出解绑提示窗口
- [实际结果] 
点击‘解除绑定’按钮后无响应

**Comment by shindouhiro** [comment]
已经修复

**Comment by duanlintai** [comment]
已修复，测试通过
