### ISSUE TITLE
首页点击‘立即购买’不能跳转到确认订单页面

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#178]
- [前置条件] 
用户已登录，进入万人车汇首页
- [操作步骤] 
点击‘立即购买’按钮
- [预期结果] 
跳转到确认订单页面
- [实际结果] 
不能跳转，一直显示订单生成中，详见下图
![default](https://user-images.githubusercontent.com/40376906/42805705-1d6b3eea-89df-11e8-9323-3b8ae1b8d1ff.jpeg)

**Comment by shindouhiro** [comment]
已经修复

**Comment by duanlintai** [comment]
测试通过，关闭issue
