### ISSUE TITLE
分享页面二维码扫描功能不能实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#179]
- [前置条件] 
用户已登录，进入个人中心页面
- [操作步骤]
1.点击我的店铺
2.点击‘正在出售的商品’
3.点击分享图标 
4.手机微信扫描二维码
- [预期结果] 
手机跳转相应页面
- [实际结果] 
网页无法打开，详见下图
![default](https://user-images.githubusercontent.com/40376906/42806061-21694b44-89e0-11e8-828e-749b5b3f9726.png)

**Comment by shindouhiro** [comment]
此问题线上不存在

**Comment by duanlintai** [comment]
已修复，测试通过
