### ISSUE TITLE
高级会员个人中心页面缺少‘我的团队’模块

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#182]
- [前置条件] 
高级会员已登录，进入万人车汇个人中心页面
- [操作步骤] 
1.点击‘我的团队’
2.进入我的团队页面，可查看我的团队详情
- [预期结果] 
我的团队显示在‘我的店铺’和‘我的订单’中间，点击我的团队跳转到相应页面
- [实际结果] 
缺少‘我的团队’模块

**Comment by shindouhiro** [comment]
以增加该模块

**Comment by duanlintai** [comment]
测试通过，关闭issue
