### ISSUE TITLE
提现界面不能加载显示，处于一直加载状态

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#184]
- [前置条件] 
用户已登录，进入财务页面
- [操作步骤] 
点击‘提现’按钮
- [预期结果] 
成功进入提现界面
- [实际结果] 
页面一直加载，不能显示
![default](https://user-images.githubusercontent.com/40376906/42811210-93797e5a-89ec-11e8-8c05-a548766dc7c8.jpeg)

**Comment by shindouhiro** [comment]
已修改，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
