### ISSUE TITLE
已授予高级会员卡用户点击‘新加商品’不能跳转，并提示推荐购买黑卡

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#185]
- [前置条件] 
普通黑卡会员已登录，进入万人车汇个人中心页面
- [操作步骤] 
1.登录testuser1
2.点击‘我的店铺’
3.点击‘新加商品’
- [预期结果]
跳转进入万人车汇商品库
- [实际结果] 
弹出推荐购买黑卡窗口

**Comment by shindouhiro** [comment]
已修改，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
