### ISSUE TITLE
用户（用户名注册，无手机号）为黑卡普通会员时正在出售商品中含有商品高级会员卡

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#187]
- [前置条件] 
黑卡普通会员用户已登录，进入万人车汇个人中心
- [操作步骤] 
1.点击我的店铺
2.点击正在出售的商品
- [预期结果] 
不能代理高级会员卡，正在出售的商品库中不能有高级会员卡
- [实际结果] 
正在出售的商品中含有高级会员卡

**Comment by shindouhiro** [comment]
已修复

**Comment by duanlintai** [comment]
已修复，测试通过
