### ISSUE TITLE
新商品发布成功后，进入鲜至前端点击产品进入产品介绍页面报错

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#193]
- [前置条件] 
进入鲜至首页
- [操作步骤] 
1.商家后台发布新商品
2.前端点击商品图片进入商品介绍页面
- [预期结果] 
成功进入产品介绍页面
- [实际结果] 
不能进入产品介绍页面，页面报错或空白，详见下图
![default](https://user-images.githubusercontent.com/40376906/43186613-ccac122e-9021-11e8-95b5-609cb1f7e6b5.jpeg)

**Comment by shindouhiro** [comment]
解决此问题，已加判断

**Comment by duanlintai** [comment]
已修复，测试通过
