### ISSUE TITLE
手机验证码登录验证码可以重复多次使用

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#214]
- [前置条件] 
进入鲜至臻品手机验证码登录页面
- [操作步骤] 
1.输入手机号码
2.点击获取验证码
3.输入手机号码收到的验证码
4.点击登录
5.点击退出登录
6.再次重复以上步骤，输入之前的验证码
- [预期结果] 
同一个验证码只能使用一次，已使用过的验证码再次使用系统提示‘验证码错误’
- [实际结果]
验证码可以多次重复使用

**Comment by simontaosim** [comment]
这个已经解决，提交测试

**Comment by duanlintai** [comment]
测试通过，关闭issue
