### ISSUE TITLE
验证待付款下点击商品‘查看详情’按钮，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#22]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的订单’ 
2.点击‘待付款’ 
3.点击商品‘查看详情’按钮
- [预期结果] 
1.跳转到我的订单页面
2.显示待付款订单
3.跳转到订单详情页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
