### ISSUE TITLE
用户通过高级会员分享购买优先会员卡后，能获得角色权限，但不能形成上下级关系，需要第二次通过分享购买才能生成上下级关系

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#225]
- [前置条件] 
已登录是高级会员用户账号
- [操作步骤] 
1.高级会员分享优选会员二维码给普通用户
2.普通用户通过二维码第一次购买高级会员分享的优选会员卡二维码
3.完成支付
4.高级会员第二次分享优选会员二维码给普通用户
5.普通用户再次购买
6.完成支付
- [预期结果] 
第一次购买成功后，获得普通会员角色权限，成为高级会员的下级
- [实际结果]
第一此购买成功后，能获得角色权限，但不能形成上下级关系，需要第二次购买才能成为高级会员的下级

**Comment by simontaosim** [comment]
修改完成，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
