### ISSUE TITLE
用户通过高级会员分享购买优选会员卡后，高级会员没有获得佣金，第二通过分享购买同时获得两份一级和二级级佣金

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#226]
- [前置条件] 
已登录高级会员用户账号
- [操作步骤] 
1.高级会员分享优选会员二维码给普通用户
2.普通用户通过二维码第一次购买高级会员分享的优选会员卡二维码
3.完成支付
4.高级会员第二次分享优选会员二维码给普通用户
5.普通用户再次购买
6.完成支付
- [预期结果] 
第一次购买，高级会员获得用户购买的一级佣金，第二次购买，高级会员还是获得用户购买的一级佣金
- [实际结果]
第一此购买，高级会员没有获得佣金，第二次通过分享购买高级会员同时获得两份 一级和二级佣金

**Comment by simontaosim** [comment]
修改完成，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
