### ISSUE TITLE
已是普通会员的用户通过高级会员分享的优选会员卡二维码购买普通会员卡不能成为高级会员的下级

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#227]
- [前置条件] 
已登录拥有高级会员权限的账号
- [操作步骤] 
1.高级会员分享优选会员卡二维码给已是普通会员的用户
2.普通会员用户通过高级会员分享的优选会员卡二维码购买
3.普通会员完成支付
- [预期结果] 
普通会员角色权限依然存在，并成为高级会员的下级
- [实际结果]
不能成为高级会员的下级

**Comment by simontaosim** [comment]
修改完成，提交测试

**Comment by duanlintai** [comment]
已修复，测试通过
