### ISSUE TITLE
高级会员分享优选会员卡给自己购买时，同时获得两份一级和二级佣金

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#228]
- [前置条件] 
登录高级会员账号
- [操作步骤] 
1.分享优选会员卡给自己购买
2.识别二维码
3.完成支付
- [预期结果] 
获得一份1级佣金
- [实际结果]
同时获得两份一级和二级佣金

**Comment by simontaosim** [comment]
已修改，提交测试

**Comment by duanlintai** [comment]
已修复
