### ISSUE TITLE
验证订单详情页面显示情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#23]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的订单’ 
2.点击‘待付款’ 
3.点击‘查看详情’按钮 
4.跳转到订单详情页面
- [预期结果] 
1.跳转到我的订单页面
2.显示待付款订单
3.跳转到订单详情页面
4.页面显示收货地址(姓名.电话和地址).待付款商品.二维码和下单时间(订单编号和创建时间)

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
