### ISSUE TITLE
验证订单详情页面二维码能否扫描跳转相应页面

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#26]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的订单’ 
2.点击‘待付款’ 
3.点击‘查看详情’按钮 
4.手机扫描二维码
- [预期结果] 
1.跳转到我的订单页面
2.显示待付款订单
3.跳转到订单详情页面
4.跳转相应页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
测试通过
