### ISSUE TITLE
验证我的订单页面点击‘已完成’系统显示情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#28]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的订单’ 
2.点击‘已完成’
- [预期结果] 
1.跳转到我的订单页面
2.显示已完成订单

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
