### ISSUE TITLE
验证新增银行卡功能能否实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#34]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击’我的银行卡‘ 
2.点击’新增‘按钮 
3.输入正确银行开户户头姓名 
4.输入正确银行卡卡号 
5.输入正确银行开户行（具体到支行）
 6.点击‘保存’按钮
- [预期结果] 
1.成功跳转到我的银行卡页面
2.成功进入新增银行卡页面
3.新增银行卡成功,并显示在我的银行卡页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见issue #150--#161
