### ISSUE TITLE
验证手机验证码登录,输入正确手机号和验证码时是否能登录成功

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#4]
- [ 预置条件]
1. 进入手机验证码登录界面

- [ 操作步骤] 
1.输入11位正确的手机号码
2.点击获取验证码
3.输入手机收到的验证码
4.点击登录/注册按钮

- [ 预期结果] 
1.
2.
3.
4.系统提示’登录成功‘，并进入万人车汇主页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见issue #140--#146
