### ISSUE TITLE
验证万人车汇商品库页面滑动鼠标滚动键，页面反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#48]
- [前置条件] 
1.用户已登录
2.进入个人中心页面
- [操作步骤] 
1.点击‘我的店铺’ 
2.点击‘正在出售商品’
3.滑动鼠标滚动键
- [预期结果] 
1.显示下拉列表‘新加商品’和‘正在出售商品’两个选项
2.成功跳转到万人车汇商品库
3.页面依次显示更多商品

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
