### ISSUE TITLE
验证黑卡会员进入财务页面时显示情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#52]
- [前置条件] 
1.用户已登录
2.进入财务页面
- [操作步骤] 
点击‘财务’模块，进入财务页面
- [预期结果] 
页面显示黑卡会员获得佣金金额,收益(今日,一周,30天),明细（收入来源,提现记录）

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
