### ISSUE TITLE
验证普通用户进入财务页面时，页面展示情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#59]
- [预置条件] 
1.用户已登录
2.进入财务页面
- [操作步骤] 
点击‘财务’模块
- [预期结果] 
佣金金额显示为0，收益（今日,一周,30天）显示为0，明细（收入来源,提现记录）显示暂无数据

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
