### ISSUE TITLE
验证点击商品图片上的‘添加购物车’按钮时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#61]
- [预置条件] 
1.用户已登录
2.进入万人车汇首页
- [操作步骤] 
点击商品图片上的'添加购物车'按钮
- [预期结果] 
系统提示‘加入购物车成功’，'立即查看'

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
