### ISSUE TITLE
验证点击‘立即查看’按钮时系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#62]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击商品图片上的‘添加购物车’按钮 
2.点击‘立即查看’
- [预期结果] 
1.系统提示‘加入购物车成功’，'立即查看'
2.成功跳转到购物车页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
