### ISSUE TITLE
验证购物车图标上是否显示与购物车内相匹配的数量

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#64]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.查看购物车图标上显示的数量 
2.进入购物车内查看
- [预期结果] 
匹配购物车内数量

**Comment by simontaosim** [comment]
开发完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
