### ISSUE TITLE
购物车内点击商品名称时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#66]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘购物车’
2.点击商品名称
- [预期结果] 
1.成功进入购物车页面
2.成功跳转到产品介绍页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
