### ISSUE TITLE
购物车内点击‘-’符号时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#67]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘购物车’图标 
2.点击‘-’符号
- [预期结果] 
1.成功进入购物车页面
2.成功减少商品数量

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
