### ISSUE TITLE
验证密码登录，输入正确手机号和密码时，系统能否登录成功

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#7]
- [ 预置条件]
进入密码登录界面 

- [ 操作步骤] 
1.输入11位正确的手机号码
2.输入正确格式密码
3.点击’登录’按钮

- [ 预期结果]
1.系统提示’登录成功，开始跳转‘
2.进入万人车汇主页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
