### ISSUE TITLE
验证购物车内商品手动输入增减数量功能能否实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#70]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击’购物车‘图标 
2.输入商品数量
- [预期结果] 
1.成功进入购物车页面
2.成功增减商品数量

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见issue #135 #136
