### ISSUE TITLE
购物车内点击’全选‘按钮时，系统能否实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#71]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击’购物车‘图标 
2.点击’全选‘按钮
- [预期结果] 
1.成功跳转到购物车页面
2.成功选中全部商品

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
