### ISSUE TITLE
验证点击’详情‘时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#74]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击商品图片 
2.点击’详情‘
- [预期结果] 
1.成功跳转到产品介绍页面
2.成功显示产品详情

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
