### ISSUE TITLE
验证点击’参数‘时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#75]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击商品图片 
2.点击’参数‘
- [预期结果] 
1.成功跳转到产品介绍页面
2.显示产品参数

**Comment by shindouhiro** [comment]
功能已完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
