### ISSUE TITLE
验证产品介绍页面点击’添加购物车’按钮时，系统提示情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#76]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击商品图片 
2.点击’添加购物车‘按钮
- [预期结果] 
1.成功跳转到产品介绍页面
2.系统提示‘加入购物车成功’,‘立即查看’

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见issue #134
