### ISSUE TITLE
验证购买产品流程功能能否实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#83]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击产品’立即购买’按钮 
2.点击’请填写您的联系方式’按钮  
3.选择地址,点击地址下方’使用此地址’按钮 
4.点击’确认订单并支付’按钮
- [预期结果] 
1.系统提示‘正在生成订单’进入确认订单页面
2.进入选择地址页面         
3.返回确认订单页面         
4.跳转到支付页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
