### ISSUE TITLE
验证订单页面点击‘请填写您的联系方式’时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#84]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’ 
2.点击‘请填写您的联系方式’
- [预期结果] 
1.进入确认订单页面
2.成功跳转到选择地址页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
