### ISSUE TITLE
验证新建联系方式功能能否实现

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#86]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’
2.点击‘请填写您的联系方式’ 
3.点击‘新建’按钮 
4.输入输入正确姓名 
5.输入正确电话号码 
6.输入正确收货地址 
7.输入正确车牌号码 
8.点击‘保存’按钮
- [预期结果] 
1.进入确认订单页面 
2.进入选择地址页面
3.成功跳转到新建联系方式页面
4.系统提示‘新建地址成功’并返回至选择地址页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见issue #113—#130
