### ISSUE TITLE
验证选择地址页面点击地址右边‘勾选框’时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#87]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’ 
2.点击‘请填写您的联系方式’
3.点击地址右边‘勾选框’
- [预期结果] 
1.进入确认订单页面 
2.进入选择地址页面
3.成功勾选地址

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
