### ISSUE TITLE
验证选择地址页面点击地址下方‘使用此地址’按钮，系统实现情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#89]
- [前置条件] 
1.用户已登录
2.进入万人车汇页面
- [操作步骤] 
1.点击‘立即购买’ 
2.点击‘请填写您的联系方式’
3.点击地址下方‘使用此地址’按钮
- [预期结果] 
1.进入确认订单页面
2.进入选择地址页面
3.系统提示'订单地址已确认'并返回确认订单页面

**Comment by shindouhiro** [comment]
功能已完成，提交测试

**Comment by duanlintai** [comment]
已验收通过
