### ISSUE TITLE
验证游客模式点击商品上面‘添加购物车’图标时，系统反应情况

### ISSUE THREAD

**Issue by duanlintai** [getHighTech/beatshop#99]
- [前置条件] 
未登录，进入万人车汇首页
- [操作步骤] 
点击商品上面‘添加购物车’图标
- [预期结果] 
系统提示‘需要先登录’并跳转到手机验证码登录页面

**Comment by shindouhiro** [comment]
功能完成，提交测试

**Comment by duanlintai** [comment]
已验收，发现BUG，详见新的issue #110
